### PR TITLE
Use CFLAGS passed to the configure script

### PR DESCRIPTION
**Pull request by fabio-porcedda**
This is also useful to support per-package staging directory within
buildroot.

Signed-off-by: Fabio Porcedda <fabio.porcedda@gmail.com>

### CODE REVIEW

**Comment by fabio-porcedda** [comment]
Can you please explain why you reverted it?

**Comment by mremond** [comment]
Yes, we need to investigate while it was not building fine while building the whole ejabberd. It broken the travis-ci testing tool. We may need to ask questions to get your help. Thanks :smile:

**Comment by fabio-porcedda** [comment]
I'm sorry to hear that.
If i understand well, the build seems fine but the testing tool found that the binary does not work fine?
Are you able to retrieve the CFLAGS passed to the configure script?

**Comment by mremond** [comment]
Yes, we will get you that, no problem. Do no worry, we will find the right combination :)

**Pull request merged**
